# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      image: 'ubuntu-latest'
    continueOnError: false
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)'
        extensionVersion: '1.$(Year:yy).$(DayOfYear).$(Rev:r)'
        updateTasksVersion: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.artifactstagingdirectory)/*.vsix'
        artifact: 'Extension'
        publishLocation: 'pipeline'

- stage: Test
  jobs:
  - job: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: false
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'

    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'VS Marketplace'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/extension/*.vsix'
        extensionTag: '-test'
        updateTasksVersion: false
        extensionVisibility: 'private'
        shareWith: 'mummy-test'
    
    - task: InstallAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'VS Marketplace'
        method: 'id'
        publisherId: 'mmajcica'
        extensionId: 'retain-release'
        extensionTag: '-test'
        accounts: 'https://dev.azure.com/mummy-test'