name: 1.$(Year:yy).$(DayOfYear).$(Rev:r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    continueOnError: false
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)/Extension'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/Extension'
        artifact: 'Extension'
        publishLocation: 'pipeline'

- stage: Test
  jobs:
  - job: Deploy
    continueOnError: false
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls'
        workingDirectory: '$(Pipeline.Workspace)'
    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'
    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Marketplace Test'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/extension/*.vsix'
        extensionTag: '-test'
        updateTasksVersion: false
        extensionVisibility: 'private'
        shareWith: 'mummy-test'
        
    - task: InstallAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Marketplace Test'
        method: 'id'
        publisherId: 'mmajcica'
        extensionId: 'retain-release'
        extensionTag: '-test'
        accounts: 'https://dev.azure.com/mummy-test'