# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      image: 'ubuntu-latest'
    continueOnError: false
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - task: CopyFiles@2
      inputs:
        Contents: |
          $(Build.SourcesDirectory)/images
          $(Build.SourcesDirectory)/task
          $(Build.SourcesDirectory)/LICENSE.txt
          $(Build.SourcesDirectory)/README.md
          $(Build.SourcesDirectory)/vss-extension.json
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.artifactstagingdirectory)'
        artifact: 'Extension'
        publishLocation: 'pipeline'

